In [1]:
"""Bag of Words"""

'Bag of Words'

In [2]:
import pandas as pd


df = pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df["Category"].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df["Spam"] = df["Category"].apply(lambda x: 1 if x == "spam" else 0)
df.head()

  Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df["Message"], df["Spam"], test_size=0.25, random_state=0)

In [6]:
print(f"X_train size: {X_train.shape}")
print(f"X_test size: {X_test.shape}")
print(f"y_train size: {y_train.shape}")
print(f"y_train size: {y_test.shape}")

X_train size: (4179,)
X_test size: (1393,)
y_train size: (4179,)
y_train size: (1393,)

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train.values)

In [8]:
X_train_vectorized.shape

(4179, 7541)

In [9]:
X_train_vectorized.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4179, 7541))

In [10]:
vectorizer.get_feature_names_out()[-1]

'〨ud'

In [11]:
vectorizer.vocabulary_

{'its': 3671,
 'going': 3085,
 'good': 3095,
 'no': 4658,
 'problem': 5289,
 'but': 1521,
 'still': 6310,
 'need': 4588,
 'little': 4044,
 'experience': 2625,
 'to': 6759,
 'understand': 6959,
 'american': 911,
 'customer': 2053,
 'voice': 7128,
 'have': 3262,
 'secret': 5812,
 'admirer': 797,
 'reveal': 5610,
 'who': 7302,
 'thinks': 6676,
 'so': 6122,
 'special': 6202,
 'call': 1548,
 '09065174042': 214,
 'opt': 4830,
 'out': 4871,
 'reply': 5563,
 'stop': 6321,
 '50': 528,
 'per': 5008,
 'msg': 4488,
 'recd': 5470,
 'cust': 2050,
 'care': 1593,
 '07821230901': 36,
 'ok': 4779,
 'huh': 3444,
 'hyde': 3468,
 'park': 4947,
 'not': 4692,
 'in': 3546,
 'mel': 4311,
 'ah': 846,
 'opps': 4829,
 'got': 3112,
 'confused': 1894,
 'anyway': 971,
 'if': 3500,
 'tt': 6883,
 'best': 1274,
 'choice': 1733,
 'den': 2165,
 'we': 7223,
 'juz': 3784,
 'take': 6515,
 'it': 3664,
 'just': 3779,
 'hopeing': 3397,
 'that': 6639,
 'wasn': 7199,
 'too': 6797,
 'pissed': 5086,
 'up': 6999,
 'remember': 5533,
 'and': 933,
 'has': 3248,
 'gone': 3092,
 'off': 4757,
 'his': 3346,
 'sisters': 6028,
 'or': 4836,
 'something': 6147,
 'accordingly': 762,
 'repeat': 5555,
 'text': 6614,
 'the': 6643,
 'word': 7393,
 'on': 4796,
 'your': 7509,
 'mobile': 4416,
 'phone': 5052,
 'send': 5845,
 'wat': 7202,
 'da': 2069,
 'model': 4425,
 'num': 4719,
 'of': 4755,
 'ur': 7014,
 'sorry': 6170,
 'll': 4052,
 'later': 3923,
 'worries': 7406,
 'hope': 3395,
 'photo': 5057,
 'shoot': 5945,
 'went': 7266,
 'well': 7260,
 'spiffing': 6218,
 'fun': 2956,
 'at': 1082,
 'workage': 7396,
 'part': 4950,
 'checking': 1692,
 'iq': 3642,
 'nokia': 4667,
 'tone': 6787,
 'mob': 4415,
 'every': 2577,
 'week': 7245,
 'txt': 6911,
 'nok': 4666,
 '87021': 676,
 '1st': 333,
 'free': 2894,
 'get': 3035,
 'txtin': 6916,
 'now': 4706,
 'tell': 6580,
 'friends': 2917,
 '150p': 301,
 '16': 311,
 'hl': 3353,
 '4info': 512,
 'hi': 3331,
 'won': 7380,
 'ard': 1012,
 'christmas': 1743,
 'do': 2294,
 'enjoy': 2511,
 'merry': 4330,
 'mas': 4253,
 'tmr': 6753,
 'then': 6657,
 'brin': 1455,
 'lar': 3914,
 'aiya': 861,
 'come': 1837,
 'mayb': 4281,
 'neva': 4613,
 'set': 5870,
 'properly': 5318,
 'help': 3305,
 'sheet': 5911,
 'wif': 7316,
 'lol': 4077,
 'didn': 2225,
 'til': 6723,
 'last': 3919,
 'nite': 4651,
 'imma': 3526,
 'definitely': 2145,
 'restock': 5595,
 'before': 1247,
 'thanksgiving': 6633,
 'let': 3978,
 'you': 7506,
 'know': 3859,
 'when': 7288,
 'guy': 3192,
 'did': 2223,
 'some': 6137,
 'bitching': 1316,
 'acted': 775,
 'like': 4005,
 'be': 1224,
 'interested': 3609,
 'buying': 1527,
 'else': 2478,
 'next': 4628,
 'he': 3272,
 'gave': 3004,
 'us': 7027,
 'for': 2848,
 've': 7073,
 'reached': 5440,
 'sch': 5777,
 'already': 896,
 'kicks': 3831,
 'hurry': 3456,
 'home': 3377,
 'soup': 6182,
 'is': 3652,
 'done': 2328,
 'this': 6681,
 'yijue': 7499,
 'regarding': 5514,
 '3230': 434,
 'textbook': 6617,
 'intro': 3621,
 'algorithms': 881,
 'second': 5809,
 'edition': 2442,
 'selling': 5841,
 'nope': 4679,
 'meanwhile': 4294,
 'she': 5910,
 'talk': 6523,
 'say': 5767,
 'make': 4207,
 'greet': 3152,
 'telling': 6581,
 'any': 961,
 'one': 4801,
 'treat': 6852,
 'me': 4287,
 'kallis': 3793,
 'ground': 3163,
 'amla': 915,
 'town': 6827,
 'durban': 2407,
 'luv': 4153,
 'ya': 7466,
 'all': 885,
 'was': 7197,
 'actual': 783,
 'exam': 2599,
 'harder': 3241,
 'than': 6628,
 'nbme': 4575,
 'posible': 5186,
 'dnt': 2293,
 'live': 4045,
 'lt': 4140,
 'gt': 3173,
 'century': 1645,
 'cm': 1790,
 'frwd': 2940,
 'thnk': 6685,
 'different': 2235,
 'wah': 7155,
 'lucky': 4144,
 'man': 4216,
 'can': 1570,
 'save': 5763,
 'money': 4441,
 'hee': 3293,
 'how': 3422,
 'din': 2244,
 'yup': 7525,
 'cut': 2057,
 'my': 4533,
 'hair': 3206,
 'cab': 1537,
 'available': 1117,
 'they': 6667,
 'pick': 5066,
 'drop': 2379,
 'door': 2335,
 'steps': 6300,
 'think': 6672,
 'waiting': 7164,
 'same': 5737,
 'bus': 1514,
 'inform': 3578,
 'there': 6662,
 'ever': 2576,
 'knw': 3863,
 'vl': 7124,
 'giv': 3059,
 'thanks': 6632,
 'kano': 3797,
 'wit': 7353,
 'family': 2671,
 'salary': 5726,
 'thank': 6631,
 'much': 4506,
 'skyped': 6053,
 'kz': 3878,
 'sura': 6446,
 'didnt': 2226,
 'pleasure': 5116,
 'company': 1854,
 'are': 1013,
 'given': 3061,
 'ultimatum': 6941,
 'oh': 4774,
 'countin': 1962,
 'down': 2348,
 'aburo': 746,
 'message': 4332,
 'sent': 5854,
 'days': 2105,
 'ago': 844,
 'watching': 7206,
 'tv': 6899,
 'meeting': 4303,
 'sun': 6425,
 'anti': 960,
 'sleep': 6059,
 'medicine': 4298,
 'where': 7291,
 'abj': 737,
 'serving': 5868,
 'staying': 6290,
 'with': 7354,
 'dad': 2072,
 'alone': 894,
 'service': 5866,
 'announcement': 946,
 'recently': 5478,
 'tried': 6858,
 'delivery': 2160,
 'were': 7269,
 'unable': 6947,
 'please': 5114,
 '07090298926': 22,
 're': 5438,
 'schedule': 5778,
 'ref': 5498,
 '9307622': 710,
 'late': 3921,
 'said': 5722,
 'website': 7235,
 'dont': 2330,
 'slippers': 6073,
 'private': 5280,
 '2003': 344,
 'account': 763,
 'statement': 6284,
 'shows': 5973,
 '800': 622,
 'un': 6946,
 'redeemed': 5495,
 'points': 5152,
 '08718738002': 144,
 'identifier': 3493,
 'code': 1809,
 '48922': 502,
 'expires': 2628,
 '21': 351,
 '11': 263,
 '04': 14,
 'xmas': 7453,
 'prize': 5282,
 'draws': 2361,
 'trying': 6875,
 'contact': 1911,
 'todays': 6767,
 'draw': 2360,
 '2000': 343,
 'guaranteed': 3176,
 '09058094565': 173,
 'from': 2934,
 'land': 3902,
 'line': 4017,
 'valid': 7055,
 '12hrs': 284,
 'only': 4807,
 'kay': 3805,
 'sat': 5751,
 'right': 5626,
 'guess': 3181,
 'which': 7296,
 'pub': 5341,
 'im': 3517,
 'as': 1050,
 'happy': 3238,
 'pig': 5076,
 'clover': 1783,
 'whatever': 7282,
 'saying': 5770,
 'aiyah': 862,
 'nydc': 4733,
 'wheellock': 7287,
 'cant': 1581,
 'pls': 5121,
 'yo': 7502,
 'by': 1534,
 'work': 7395,
 'buzy': 1529,
 'princess': 5271,
 'love': 4117,
 'times': 6727,
 'night': 4640,
 'thats': 6642,
 'latest': 3924,
 'ipod': 3641,
 'mp3': 4482,
 'player': 5108,
 '400': 472,
 'proze': 5330,
 'win': 7328,
 '83355': 652,
 'norcorp': 4681,
 'ltd': 4141,
 'mtmsgrcvd18': 4502,
 'eldest': 2471,
 'staff': 6261,
 'placement': 5094,
 'training': 6835,
 'amrita': 924,
 'college': 1826,
 'way': 7218,
 'put': 5362,
 'skip': 6048,
 'outside': 4881,
 'front': 2937,
 'house': 3419,
 'see': 5821,
 'pull': 5345,
 'god': 3080,
 'almost': 893,
 'coming': 1843,
 'funeral': 2961,
 'jst': 3764,
 'change': 1659,
 'tat': 6541,
 'would': 7416,
 'mom': 4434,
 'fit': 2780,
 'whole': 7304,
 'crazy': 1990,
 'terrible': 6602,
 'am': 907,
 'dear': 2116,
 'why': 7309,
 'mood': 4452,
 'drive': 2373,
 'brother': 1471,
 'lemme': 3968,
 'swing': 6485,
 'basically': 1197,
 'time': 6726,
 'after': 828,
 'semester': 5843,
 'forgot': 2861,
 'ask': 1060,
 'smth': 6108,
 'card': 1590,
 'present': 5250,
 'lei': 3966,
 'want': 7184,
 'write': 7425,
 'sign': 5995,
 'nooooooo': 4677,
 'gonna': 3094,
 'bored': 1382,
 'death': 2120,
 'day': 2104,
 'cable': 1539,
 'internet': 3614,
 'outage': 4872,
 'video': 7094,
 'camera': 1567,
 'phones': 5056,
 'half': 3209,
 'price': 5264,
 'rental': 5550,
 '12': 274,
 'mths': 4499,
 '500': 529,
 'cross': 2011,
 'ntwk': 4715,
 'mins': 4373,
 '100': 251,
 'txts': 6918,
 'mobileupd8': 4420,
 '08001950382': 50,
 'call2optout': 1550,
 '674': 575,
 'haha': 3202,
 'used': 7032,
 'driving': 2376,
 'usf': 7036,
 'lot': 4106,
 'stoners': 6318,
 '10': 250,
 'min': 4360,
 'anything': 968,
 'about': 739,
 'sure': 6447,
 'xavier': 7449,
 'smoke': 6099,
 'because': 1233,
 'don': 2326,
 'being': 1258,
 'told': 6774,
 'alright': 897,
 'bring': 1456,
 'changes': 1661,
 '6hrs': 592,
 'even': 2570,
 'appendix': 987,
 'age': 837,
 'range': 5421,
 'however': 3426,
 'impossible': 3537,
 'chill': 1720,
 'recpt': 5491,
 'ordered': 4844,
 'ringtone': 5634,
 'order': 4843,
 'processed': 5296,
 'official': 4767,
 'england': 2509,
 'poly': 5160,
 'colour': 1828,
 'flag': 2789,
 'yer': 7489,
 'tonights': 6794,
 'game': 2985,
 '84199': 662,
 'optout': 4835,
 'eng': 2504,
 'box39822': 1409,
 'w111wx': 7144,
 'vodafone': 7126,
 'numbers': 4721,
 'ending': 2498,
 '0089': 4,
 'four': 2878,
 'digits': 2240,
 'selected': 5834,
 'received': 5475,
 '350': 439,
 'award': 1132,
 'number': 4720,
 'matches': 4261,
 '09063442151': 202,
 'claim': 1751,
 'wine': 7335,
 'dine': 2245,
 'lady': 3895,
 '4882': 501,
 'receive': 5473,
 '09064019014': 211,
 'check': 1688,
 'detailed': 2196,
 'gets': 3038,
 'these': 6664,
 'questions': 5381,
 '4mths': 514,
 'orange': 4840,
 'had': 3199,
 '11mths': 272,
 'mobilesdirect': 4418,
 '08000938767': 49,
 'update': 7003,
 'or2stoptxt': 4838,
 'came': 1566,
 'hostel': 3409,
 'probably': 5288,
 'gas': 2999,
 'cash': 1614,
 'tomorrow': 6785,
 'claire': 1753,
 'here': 3319,
 'havin': 3267,
 'borin': 1383,
 'wanna': 7182,
 'cum': 2041,
 'over': 4887,
 '2nite': 402,
 'chat': 1678,
 '09099725823': 240,
 'xx': 7456,
 'calls': 1561,
 'minmoremobsemspobox45po139wa': 4370,
 'fine': 2762,
 'babes': 1153,
 'aint': 856,
 'been': 1241,
 'tho': 6688,
 'saw': 5766,
 'scary': 5775,
 'movie': 4478,
 'yest': 7491,
 'quite': 5386,
 'funny': 2964,
 '2mrw': 397,
 'afternoon': 830,
 'mall': 4214,
 'sumthin': 6424,
 'shant': 5902,
 'disturb': 2281,
 'anymore': 964,
 'jia': 3727,
 'wants': 7188,
 'morning': 4459,
 'plz': 5127,
 'sir': 6024,
 'tonight': 6793,
 'very': 7085,
 'environment': 2531,
 'terrific': 6603,
 'food': 2838,
 'really': 5456,
 'nice': 4632,
 'simply': 6010,
 'sitting': 6033,
 'match': 4259,
 'office': 4766,
 'aight': 854,
 'around': 1037,
 'hmmm': 3358,
 'opener': 4818,
 'leh': 3965,
 'go': 3076,
 'tuition': 6889,
 'looking': 4091,
 'empty': 2493,
 'slots': 6074,
 'lessons': 3977,
 'dai': 2074,
 'what': 7281,
 'resume': 5602,
 'id': 3488,
 'will': 7325,
 'gentle': 3025,
 'baby': 1155,
 'soon': 6161,
 'taking': 6520,
 'inches': 3550,
 'deep': 2137,
 'inside': 3595,
 'tight': 6720,
 'pussy': 5361,
 'gotta': 3118,
 'hit': 3348,
 'people': 5006,
 'first': 2777,
 'amp': 922,
 'coherently': 1811,
 'twenty': 6902,
 'major': 4206,
 'roles': 5657,
 'community': 1849,
 'outreach': 4879,
 'rock': 5650,
 'dude': 2397,
 'arrested': 1041,
 'other': 4862,
 'sister': 6027,
 'earn': 2422,
 'more': 4455,
 'leave': 3954,
 'always': 905,
 'ignorant': 3504,
 'medical': 4297,
 '7pm': 618,
 'forward': 2874,
 'macha': 4177,
 'feel': 2710,
 'upset': 7011,
 'assume': 1075,
 'mindset': 4363,
 'believe': 1259,
 'evening': 2571,
 'wonderful': 7384,
 'plans': 5103,
 'both': 1390,
 'life': 3993,
 'begin': 1251,
 'again': 835,
 'anytime': 970,
 'new': 4619,
 'address': 792,
 'apples': 989,
 'pairs': 4920,
 'malarky': 4212,
 'complete': 1864,
 'gist': 3058,
 'especially': 2554,
 'since': 6012,
 'boston': 1388,
 'personal': 5028,
 'woulda': 7417,
 'changed': 1660,
 'realized': 5454,
 'nyc': 4732,
 'says': 5771,
 'drug': 2384,
 'able': 738,
 'eat': 2433,
 'sleeping': 6061,
 'nt': 4713,
 'feeling': 2712,
 'escape': 2550,
 'theatre': 6647,
 'watch': 7203,
 'kavalan': 3804,
 'few': 2726,
 'minutes': 4377,
 'continent': 1919,
 'keep': 3809,
 'yourself': 7514,
 'safe': 5717,
 'miss': 4384,
 'envy': 2532,
 'everyone': 2582,
 'real': 5448,
 '000': 1,
 'call09050000327': 1549,
 'pretty': 5259,
 'girl': 3054,
 'does': 2305,
 'stay': 6287,
 'bed': 1238,
 'doesn': 2307,
 'recovery': 5490,
 'rather': 5426,
 'pass': 4961,
 'while': 7297,
 'having': 3268,
 'cooped': 1936,
 'seeing': 5823,
 'missed': 4386,
 'gr8': 3126,
 'hey': 3327,
 'gals': 2982,
 'meet': 4301,
 'dinner': 2249,
 'nìte': 4737,
 'jess': 3720,
 'eve': 2568,
 'xxx': 7458,
 'luton': 4152,
 '0125698789': 7,
 'ring': 5632,
 'pictures': 5072,
 'facebook': 2650,
 'thought': 6692,
 'living': 4049,
 'perfect': 5012,
 'partner': 4955,
 'back': 1159,
 'name': 4552,
 'join': 3741,
 '100p': 254,
 'sms': 6103,
 'thing': 6670,
 'sentence': 5855,
 'into': 3619,
 'concentrate': 1877,
 'educational': 2446,
 'career': 1596,
 'leaving': 3956,
 'wanted': 7186,
 'holy': 3376,
 'shit': 5933,
 'guys': 3193,
 'weren': 7270,
 'kidding': 3832,
 'bud': 1489,
 'started': 6278,
 'skye': 6051,
 'wife': 7317,
 'knew': 3856,
 'murder': 4520,
 'exactly': 2598,
 'slow': 6075,
 'using': 7038,
 'biola': 1305,
 'fne': 2824,
 'glad': 3064,
 'following': 2831,
 'dreams': 2363,
 'goodo': 3104,
 'yes': 7490,
 'must': 4527,
 'speak': 6200,
 'friday': 2912,
 'egg': 2456,
 'potato': 5202,
 'ratio': 5427,
 'tortilla': 6813,
 'needed': 4589,
 'finally': 2756,
 'lunch': 4150,
 'today': 6766,
 'stomach': 6315,
 'thru': 6706,
 'trauma': 6844,
 'swear': 6474,
 'better': 1279,
 'lose': 4100,
 'weight': 7251,
 'actually': 784,
 'weeks': 7249,
 'start': 6277,
 'putting': 5365,
 'ad': 785,
 'docs': 2299,
 'appointments': 995,
 'tired': 6733,
 'them': 6653,
 'shoving': 5965,
 'stuff': 6367,
 'ugh': 6934,
 'couldn': 1960,
 'normal': 4685,
 'body': 1361,
 'double': 2342,
 'linerental': 4020,
 'motorola': 4471,
 'sonyericsson': 6160,
 'tooth': 6801,
 '08000839402': 47,
 'or2optout': 4837,
 'hv9d': 3465,
 'member': 4316,
 'aunt': 1108,
 'flow': 2811,
 'visit': 7116,
 'months': 4451,
 'cause': 1626,
 'developed': 2203,
 'ovarian': 4886,
 'cysts': 2068,
 'bc': 1214,
 'shrink': 5976,
 'okmail': 4785,
 'dave': 2102,
 'final': 2754,
 'notice': 4698,
 'collect': 1821,
 'tenerife': 6594,
 'holiday': 3372,
 '5000': 530,
 '09061743806': 194,
 'landline': 3904,
 'tcs': 6556,
 'sae': 5715,
 'box326': 1406,
 'cw25wx': 2065,
 '150ppm': 305,
 '87131': 681,
 'true': 6867,
 '0845': 61,
 '2814032': 370,
 'tones': 6788,
 '3x': 469,
 '150pw': 307,
 'nd': 4576,
 'indeed': 3565,
 'either': 2464,
 'monday': 4439,
 'dentists': 2171,
 'an': 929,
 'hour': 3417,
 'isn': 3659,
 'frnd': 2925,
 'necesity': 4582,
 'imagine': 3521,
 'urself': 7026,
 'witout': 7359,
 'hw': 3467,
 'colleg': 1825,
 'wth': 7437,
 'cell': 1642,
 'abt': 744,
 'functions': 2958,
 'events': 2574,
 'espe': 2553,
 'cared': 1595,
 'irritated': 3648,
 '4wrd': 525,
 'those': 6689,
 'loving': 4127,
 'frnds': 2926,
 'wthout': 7438,
 'whom': 7305,
 'takecare': 6516,
 'goodmorning': 3100,
 'hospital': 3407,
 'return': 5606,
 'hungry': 3450,
 'wot': 7413,
 'weirdo': 7255,
 'hows': 3427,
 'resizing': 5581,
 'bugis': 1497,
 '930': 709,
 'jokin': 3747,
 'oni': 4803,
 'busy': 1520,
 'wun': 7443,
 'surfing': 6450,
 'drink': 2368,
 'plenty': 5118,
 'water': 7208,
 'trip': 6859,
 'tiring': 6734,
 'lor': 4098,
 'uni': 6971,
 'starts': 6280,
 'cos': 1948,
 'modules': 4428,
 'jus': 3778,
 'concentrating': 1878,
 'yr': 7518,
 'project': 5305,
 'wow': 7420,
 'impressed': 3540,
 'funs': 2965,
 'shopping': 5948,
 'try': 6874,
 'lost': 4105,
 'fact': 2651,
 'tee': 6571,
 'feb': 2706,
 'dis': 2261,
 'valued': 7059,
 'evn': 2591,
 'comes': 1839,
 'married': 4248,
 'person': 5026,
 'ignore': 3505,
 'evr': 2593,
 'thanx': 6636,
 'school': 5779,
 'mobs': 4421,
 'direct': 2254,
 '2u': 410,
 'rply': 5678,
 'title': 6740,
 '8007': 625,
 'eg': 2454,
 'breathe1': 1442,
 'titles': 6741,
 'crazyin': 1991,
 'sleepingwith': 6062,
 'finest': 2763,
 'ymca': 7501,
 'getzed': 3042,
 'co': 1798,
 'uk': 6937,
 'pobox365o4w45wq': 5139,
 '300p': 422,
 'unique': 6974,
 'user': 7034,
 '1172': 270,
 'removal': 5542,
 '87239': 683,
 'services': 5867,
 '08708034412': 87,
 'aaooooright': 729,
 'buy': 1524,
 'newspapers': 4627,
 'pic': 5065,
 'msgs': 4494,
 'balance': 1169,
 'currently': 2046,
 'pounds': 5208,
 'maximize': 4278,
 '86688': 674,
 'cc': 1631,
 '08718720201': 132,
 'po': 5129,
 'box': 1401,
 '114': 267,
 '14': 289,
 'tcr': 6555,
 'w1': 7143,
 'finished': 2766,
 'daddy': 2073,
 'scream': 5792,
 'slap': 6057,
 'ass': 1069,
 'dick': 2221,
 'men': 4322,
 'sounds': 6180,
 'someone': 6141,
 'testing': 6610,
 'sayy': 5772,
 'pay': 4981,
 'stock': 6312,
 'comin': 1842,
 '1030': 257,
 'basic': 1196,
 'yoga': 7503,
 'course': 1968,
 'pilates': 5077,
 'her': 3318,
 'aww': 1137,
 'nearly': 4581,
 'dead': 2112,
 'jez': 3725,
 'iscoming': 3654,
 'todo': 6768,
 'workand': 7397,
 'whilltake': 7298,
 'forever': 2853,
 'greatest': 3148,
 'test': 6609,
 'courage': 1966,
 'earth': 2425,
 'bear': 1227,
 'defeat': 2142,
 'without': 7357,
 'losing': 4103,
 'heart': 3287,
 'gn': 3072,
 'tc': 6554,
 'room': 5661,
 'knocking': 3858,
 'nothing': 4697,
 'easy': 2432,
 'reason': 5461,
 ...}

In [12]:
import numpy as np


np.where(X_train_vectorized.toarray()[0] != 0)

(array([ 911, 1521, 2053, 2625, 3085, 3095, 3671, 4044, 4588, 4658, 5289,
        6310, 6759, 6959, 7128]),)

In [13]:
# Build machine learning model
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

MultinomialNB()

In [14]:
X_test_vectorizer = vectorizer.transform(X_test)
y_prediction = model.predict(X_test_vectorizer)
y_prediction

array([0, 1, 0, ..., 1, 0, 0], shape=(1393,))

In [15]:
from sklearn.metrics import accuracy_score, classification_report

print((f"Accuracy: {accuracy_score(y_test, y_prediction)}"))
print(f"Classification Report: \n {classification_report(y_test, y_prediction)}")

Accuracy: 0.9877961234745154
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      1208
           1       0.99      0.92      0.95       185

    accuracy                           0.99      1393
   macro avg       0.99      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393

In [16]:
emails = [
    "Hey mohan, can we get together to watch footbal game tomorrow?",
    "Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!"
]

emails_count_vector = vectorizer.transform(emails)
model.predict(emails_count_vector)

array([0, 1])

In [17]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("naive_bayes_classifier", MultinomialNB()), 
])

In [18]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('naive_bayes_classifier', MultinomialNB())])

In [19]:
emails = [
    "Hey mohan, can we get together to watch footbal game tomorrow?",
    "Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!"
]

pipeline.predict(emails)

array([0, 1])

In [20]:
print((f"Accuracy: {accuracy_score(y_test, pipeline.predict(X_test))}"))
print(f"Classification Report: \n {classification_report(y_test, pipeline.predict(X_test))}")

Accuracy: 0.9877961234745154
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      1208
           1       0.99      0.92      0.95       185

    accuracy                           0.99      1393
   macro avg       0.99      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393

In [21]:
"""Exercise"""
import pandas as pd
# Load the dataset
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [22]:
# Print the shape of the dataset
df.shape

(50000, 2)

In [23]:
df["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [24]:
df["sentiment_boolean"] = df["sentiment"].apply(lambda x: 1 if x == "positive" else 0)
df.head()

,review,sentiment,sentiment_boolean
0,One of the other reviewers has mentioned that ...,positive,1
1,A wonderful little production. <br /><br />The...,positive,1
2,I thought this was a wonderful way to spend ti...,positive,1
3,Basically there's a family where a little boy ...,negative,0
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df["review"], df["sentiment_boolean"], test_size=0.2, random_state=0)

In [26]:
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (40000,)
y_train shape: (40000,)
X_test shape: (10000,)
y_test shape: (10000,)

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train.values)
X_test_vectorizer = vectorizer.transform(X_test.values)

In [28]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=50, criterion="entropy", random_state=0)
model.fit(X_train_vectorized, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=50, random_state=0)

In [29]:
from sklearn.metrics import accuracy_score, classification_report

print(f"Accuracy Score: {accuracy_score(y_test, model.predict(X_test_vectorizer))}")
print(f"Classification repost: \n {classification_report(y_test, model.predict(X_test_vectorizer))}")

Accuracy Score: 0.8352

Classification repost:
               precision    recall  f1-score   support

           0       0.83      0.84      0.84      5035
           1       0.84      0.83      0.83      4965

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000

In [30]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("random_forest_classifier", RandomForestClassifier(n_estimators=50, criterion="entropy", random_state=0))
])

In [31]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('random_forest_classifier',
                 RandomForestClassifier(criterion='entropy', n_estimators=50,
                                        random_state=0))])

In [32]:
print(f"Accuracy Score: {accuracy_score(y_test, pipeline.predict(X_test))}")
print(f"Classification repost: \n {classification_report(y_test, pipeline.predict(X_test))}")

Accuracy Score: 0.8352
Classification repost:
               precision    recall  f1-score   support

           0       0.83      0.84      0.84      5035
           1       0.84      0.83      0.83      4965

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000

In [33]:
from sklearn.neighbors import KNeighborsClassifier

pipeline = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("knn_classifier", KNeighborsClassifier(n_neighbors=10, metric="euclidean"))
])

In [34]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('knn_classifier',
                 KNeighborsClassifier(metric='euclidean', n_neighbors=10))])

In [35]:
print(f"Accuracy Score: {accuracy_score(y_test, pipeline.predict(X_test))}")
print(f"Classification repost: \n {classification_report(y_test, pipeline.predict(X_test))}")

Accuracy Score: 0.6558
Classification repost:
               precision    recall  f1-score   support

           0       0.65      0.67      0.66      5035
           1       0.66      0.64      0.65      4965

    accuracy                           0.66     10000
   macro avg       0.66      0.66      0.66     10000
weighted avg       0.66      0.66      0.66     10000

In [36]:
pipeline = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("naive_bayes_classifier", MultinomialNB())
])

pipeline.fit(X_train, y_train)

print(f"Accuracy Score: {accuracy_score(y_test, pipeline.predict(X_test))}")
print(f"Classification repost: \n {classification_report(y_test, pipeline.predict(X_test))}")

Accuracy Score: 0.844
Classification repost:
               precision    recall  f1-score   support

           0       0.82      0.88      0.85      5035
           1       0.87      0.81      0.84      4965

    accuracy                           0.84     10000
   macro avg       0.85      0.84      0.84     10000
weighted avg       0.85      0.84      0.84     10000